import { getDb } from "../db/index.js";
import type { MemoryTier } from "../types.js";
import { generateEmbedding, encodeEmbedding } from "./embeddings.js";

export interface SaveMemoryArgs {
  agentId: string;
  content: string;
  category?: MemoryTier;
  keywords?: string;
  sector?: string;
  autoGenerated?: boolean;
}

export function saveMemory(a: SaveMemoryArgs): number {
  const r = getDb()
    .prepare(
      `INSERT INTO memories (agent_id, category, content, keywords, sector, auto_generated)
       VALUES (?, ?, ?, ?, ?, ?)`
    )
    .run(a.agentId, a.category ?? "warm", a.content, a.keywords ?? null, a.sector ?? null, a.autoGenerated ? 1 : 0);
  const id = Number(r.lastInsertRowid);
  // Fire and forget, deliberately NOT awaited: the memory is the asset, the vector is an enhancement.
  // Ollama being down, slow or restarting must never fail or delay a save — a missing vector is
  // recoverable by backfillEmbeddings(), a lost memory is not.
  void attachEmbedding(id, embeddableText(a.content, a.keywords));
  return id;
}

/** What we actually embed: the content plus its keywords, so a hand-tagged term is searchable too. */
function embeddableText(content: string, keywords?: string | null): string {
  return keywords?.trim() ? `${content}\n${keywords}` : content;
}

/**
 * Compute and store the vector for one memory. Returns whether a vector was written.
 *
 * Never throws: callers include the fire-and-forget path in saveMemory, where an unhandled rejection
 * would be an unhandled promise rejection in the engine process.
 */
export async function attachEmbedding(id: number, text: string): Promise<boolean> {
  try {
    const v = await generateEmbedding(text);
    if (!v) return false;
    getDb().prepare("UPDATE memories SET embedding = ? WHERE id = ?").run(encodeEmbedding(v), id);
    return true;
  } catch {
    return false;
  }
}

/**
 * Coverage counter. This exists because the gap it measures went unnoticed for EIGHT WEEKS: the
 * column was there, saves succeeded, FTS recall worked, and nothing anywhere reported that not one
 * vector had been written since the 2026-06-09 migration.
 */
export function countEmbeddings(): { total: number; embedded: number; missing: number } {
  const r = getDb()
    .prepare("SELECT COUNT(*) total, SUM(embedding IS NOT NULL) embedded FROM memories")
    .get() as { total: number; embedded: number | null };
  const total = Number(r.total ?? 0);
  const embedded = Number(r.embedded ?? 0);
  return { total, embedded, missing: total - embedded };
}

/**
 * Backfill vectors for rows that have none, oldest first. Bounded per call so it can be run
 * repeatedly (cron, or by hand) without hogging the local model. Returns what it managed.
 */
export async function backfillEmbeddings(limit = 200): Promise<{ attempted: number; written: number }> {
  const rows = getDb()
    .prepare("SELECT id, content, keywords FROM memories WHERE embedding IS NULL ORDER BY id LIMIT ?")
    .all(limit) as { id: number; content: string; keywords: string | null }[];
  let written = 0;
  for (const row of rows) {
    if (await attachEmbedding(row.id, embeddableText(row.content, row.keywords))) written++;
  }
  return { attempted: rows.length, written };
}

export interface SearchArgs {
  agentId?: string;
  q?: string;
  /** one tier, or a set of tiers (IN-filtered) — e.g. ['hot','warm'] for the always-bundle */
  category?: MemoryTier | MemoryTier[];
  limit?: number;
}

export interface MemoryRow {
  id: number;
  agent_id: string;
  category: string;
  content: string;
  keywords: string | null;
  salience: number;
  created_at: number;
  accessed_at: number;
}

/** FTS5 search when `q` is given; otherwise most-recent, filterable by agent/category. */
export function searchMemories(a: SearchArgs): MemoryRow[] {
  const db = getDb();
  const limit = Math.min(a.limit ?? 50, 500);
  const where: string[] = [];
  const params: unknown[] = [];

  if (a.q && a.q.trim()) {
    where.push("m.id IN (SELECT rowid FROM memories_fts WHERE memories_fts MATCH ?)");
    params.push(ftsQuery(a.q));
  }
  if (a.agentId) {
    where.push("m.agent_id = ?");
    params.push(a.agentId);
  }
  if (a.category) {
    // single tier -> "= ?"; a set -> "IN (?,?,…)". Both hit idx_memories_agent_cat(agent_id, category).
    const cats = Array.isArray(a.category) ? a.category : [a.category];
    if (cats.length) {
      where.push(`m.category IN (${cats.map(() => "?").join(",")})`);
      params.push(...cats);
    }
  }
  const clause = where.length ? `WHERE ${where.join(" AND ")}` : "";
  params.push(limit);
  return db
    .prepare(
      `SELECT m.id, m.agent_id, m.category, m.content, m.keywords, m.salience, m.created_at, m.accessed_at
       FROM memories m ${clause} ORDER BY m.created_at DESC LIMIT ?`
    )
    .all(...params) as MemoryRow[];
}

/** Sanitize free text into a safe FTS5 MATCH query (quoted terms, OR-joined). */
function ftsQuery(q: string): string {
  const terms = q
    .toLowerCase()
    .replace(/["()*]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .map((t) => `"${t}"`);
  return terms.length ? terms.join(" OR ") : `""`;
}
