import { getDb } from "../db/index.js";
import type { MemoryTier } from "../types.js";
import { generateEmbedding, encodeEmbedding, decodeEmbedding, cosineSimilarity, EXPECTED_DIM } from "./embeddings.js";

export interface SaveMemoryArgs {
  agentId: string;
  content: string;
  category?: MemoryTier;
  keywords?: string;
  sector?: string;
  autoGenerated?: boolean;
}

export function saveMemory(a: SaveMemoryArgs): number {
  const r = getDb()
    .prepare(
      `INSERT INTO memories (agent_id, category, content, keywords, sector, auto_generated)
       VALUES (?, ?, ?, ?, ?, ?)`
    )
    .run(a.agentId, a.category ?? "warm", a.content, a.keywords ?? null, a.sector ?? null, a.autoGenerated ? 1 : 0);
  const id = Number(r.lastInsertRowid);
  // Fire and forget, deliberately NOT awaited: the memory is the asset, the vector is an enhancement.
  // Ollama being down, slow or restarting must never fail or delay a save — a missing vector is
  // recoverable by backfillEmbeddings(), a lost memory is not.
  void attachEmbedding(id, embeddableText(a.content, a.keywords));
  return id;
}

/** What we actually embed: the content plus its keywords, so a hand-tagged term is searchable too. */
function embeddableText(content: string, keywords?: string | null): string {
  return keywords?.trim() ? `${content}\n${keywords}` : content;
}

/**
 * Compute and store the vector for one memory. Returns whether a vector was written.
 *
 * Never throws: callers include the fire-and-forget path in saveMemory, where an unhandled rejection
 * would be an unhandled promise rejection in the engine process.
 */
export async function attachEmbedding(id: number, text: string): Promise<boolean> {
  try {
    const v = await generateEmbedding(text);
    if (!v) return false;
    const r = getDb().prepare("UPDATE memories SET embedding = ? WHERE id = ?").run(encodeEmbedding(v), id);
    return r.changes > 0; // a zero-row UPDATE is not a success — the row was deleted meanwhile
  } catch {
    return false;
  }
}

/**
 * Coverage counter. This exists because the gap it measures went unnoticed for EIGHT WEEKS: the
 * column was there, saves succeeded, FTS recall worked, and nothing anywhere reported that not one
 * vector had been written since the 2026-06-09 migration.
 */
export function countEmbeddings(): {
  total: number;
  embedded: number;
  missing: number;
  /** stored but the wrong length: present, counted as covered, yet semantically dead */
  wrongDim: number;
  /** embedded MINUS wrongDim — the number that actually means anything */
  usable: number;
} {
  const r = getDb()
    .prepare(
      `SELECT COUNT(*) total,
              SUM(embedding IS NOT NULL) embedded,
              SUM(embedding IS NOT NULL AND json_array_length(embedding) != ?) wrongDim
         FROM memories`
    )
    .get(EXPECTED_DIM) as { total: number; embedded: number | null; wrongDim: number | null };
  const total = Number(r.total ?? 0);
  const embedded = Number(r.embedded ?? 0);
  const wrongDim = Number(r.wrongDim ?? 0);
  return { total, embedded, missing: total - embedded, wrongDim, usable: embedded - wrongDim };
}

/**
 * Backfill vectors for rows that have none, oldest first. Bounded per call so it can be run
 * repeatedly (cron, or by hand) without hogging the local model. Returns what it managed.
 */
export async function backfillEmbeddings(limit = 200): Promise<{ attempted: number; written: number }> {
  const rows = getDb()
    // Re-attempt wrong-length vectors too, not just NULLs: a transient bad model response would
    // otherwise be permanent, because the row looks "covered" forever.
    .prepare(
      `SELECT id, content, keywords FROM memories
        WHERE embedding IS NULL OR json_array_length(embedding) != ?
        ORDER BY id LIMIT ?`
    )
    .all(EXPECTED_DIM, limit) as { id: number; content: string; keywords: string | null }[];
  let written = 0;
  for (const row of rows) {
    if (await attachEmbedding(row.id, embeddableText(row.content, row.keywords))) written++;
  }
  return { attempted: rows.length, written };
}

export interface SearchArgs {
  agentId?: string;
  q?: string;
  /** one tier, or a set of tiers (IN-filtered) — e.g. ['hot','warm'] for the always-bundle */
  category?: MemoryTier | MemoryTier[];
  limit?: number;
}

export interface MemoryRow {
  id: number;
  agent_id: string;
  category: string;
  content: string;
  keywords: string | null;
  salience: number;
  created_at: number;
  accessed_at: number;
}

/** FTS5 search when `q` is given; otherwise most-recent, filterable by agent/category. */
export function searchMemories(a: SearchArgs): MemoryRow[] {
  const db = getDb();
  const limit = Math.min(a.limit ?? 50, 500);
  const where: string[] = [];
  const params: unknown[] = [];

  if (a.q && a.q.trim()) {
    where.push("m.id IN (SELECT rowid FROM memories_fts WHERE memories_fts MATCH ?)");
    params.push(ftsQuery(a.q));
  }
  if (a.agentId) {
    where.push("m.agent_id = ?");
    params.push(a.agentId);
  }
  if (a.category) {
    // single tier -> "= ?"; a set -> "IN (?,?,…)". Both hit idx_memories_agent_cat(agent_id, category).
    const cats = Array.isArray(a.category) ? a.category : [a.category];
    if (cats.length) {
      where.push(`m.category IN (${cats.map(() => "?").join(",")})`);
      params.push(...cats);
    }
  }
  const clause = where.length ? `WHERE ${where.join(" AND ")}` : "";
  params.push(limit);
  return db
    .prepare(
      // salience FIRST: it is the only way a curated core fact ("the flat is 3 rooms") can outrank 377
      // newer warm memories for the handful of always-loaded slots. Recency breaks ties.
      `SELECT m.id, m.agent_id, m.category, m.content, m.keywords, m.salience, m.created_at, m.accessed_at
       FROM memories m ${clause} ORDER BY m.salience DESC, m.created_at DESC LIMIT ?`
    )
    .all(...params) as MemoryRow[];
}

/** Sanitize free text into a safe FTS5 MATCH query (quoted terms, OR-joined). */
function ftsQuery(q: string): string {
  const terms = q
    .toLowerCase()
    .replace(/["()*]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .map((t) => `"${t}"`);
  return terms.length ? terms.join(" OR ") : `""`;
}

export interface VectorSearchArgs {
  agentId?: string;
  category?: MemoryTier | MemoryTier[];
  queryVector: number[];
  limit?: number;
  /** minimum cosine similarity to be worth surfacing at all */
  floor?: number;
}

/**
 * Rank memories by MEANING against a query vector.
 *
 * Measured need: over the real corpus, FTS topical search returned the same irrelevant row for five
 * unrelated queries, because ftsQuery OR-joins stopwords so nearly everything matches and the result
 * collapses to "most recent". Vectors put the right memory first in 4 of those 5.
 *
 * Scored in JS rather than SQL because SQLite has no vector type here; at a few thousand rows this is
 * a sub-millisecond scan. Every comparison goes through cosineSimilarity, which returns 0 on a length
 * mismatch, so a legacy or malformed vector is ranked out rather than raw-indexed (Toby's gate).
 */
export function searchMemoriesByVector(a: VectorSearchArgs): MemoryRow[] {
  const cats = a.category ? (Array.isArray(a.category) ? a.category : [a.category]) : [];
  const where: string[] = ["embedding IS NOT NULL"];
  const params: unknown[] = [];
  if (a.agentId) {
    where.push("agent_id = ?");
    params.push(a.agentId);
  }
  if (cats.length) {
    where.push(`category IN (${cats.map(() => "?").join(",")})`);
    params.push(...cats);
  }
  const rows = getDb()
    .prepare(
      `SELECT id, agent_id, category, content, keywords, salience, created_at, accessed_at, embedding
         FROM memories WHERE ${where.join(" AND ")}`
    )
    .all(...params) as (MemoryRow & { embedding: string })[];

  const floor = a.floor ?? 0.3;
  return rows
    .map((r) => ({ r, score: cosineSimilarity(a.queryVector, decodeEmbedding(r.embedding) ?? []) }))
    .filter((x) => x.score >= floor)
    .sort((x, y) => y.score - x.score)
    .slice(0, a.limit ?? 6)
    .map(({ r }) => {
      const { embedding: _drop, ...row } = r;
      return row as MemoryRow;
    });
}

/**
 * On-demand memory search, meaning FIRST and keywords SECOND.
 *
 * Backs GET /api/memories?q=, which is the path an agent uses when it deliberately goes looking —
 * including because the recall preamble tells it to. Until 2026-08-03 that path was keyword-only, so
 * the automatic slice understood meaning while the deliberate search did not.
 *
 * Vector hits lead because ftsQuery OR-joins stopwords and collapses to "most recent". Keyword hits
 * still fill the remaining slots, because they beat vectors at exact strings: invoice numbers, ids,
 * account numbers, proper nouns. Embedding is best-effort with a short leash — if it fails, this
 * returns precisely what searchMemories would have.
 */
export async function searchMemoriesHybrid(
  a: SearchArgs & { embedTimeoutMs?: number }
): Promise<MemoryRow[]> {
  const limit = Math.min(a.limit ?? 50, 500);
  const keyword = () => searchMemories({ ...a, limit });
  if (!a.q || !a.q.trim()) return keyword();

  let qv: number[] | null = null;
  try {
    qv = await Promise.race([
      generateEmbedding(a.q),
      new Promise<null>((r) => setTimeout(() => r(null), a.embedTimeoutMs ?? 2500)),
    ]);
  } catch {
    qv = null; // search must never fail because the embedder is unavailable
  }
  if (!qv?.length) return keyword();

  // Give each side a GUARANTEED share instead of concatenating. Straight concatenation let the vector
  // side fill every slot, so a query for an exact invoice number returned 8 semantically-adjacent rows
  // and not the row containing the string. Same starvation the topical reserve fixes in recall.
  // Keywords get a SMALL absolute share, never half. FTS output here is measurably noisy, so at a
  // small limit a half-share pushed the correct semantic answer out of the results entirely: asking
  // "how many rooms does the rental flat have" with limit=3 returned two vector hits plus one piece of
  // FTS noise, dropping the flat-specs memory that scored 0.641 and ranked 3rd.
  const keywordShare = Math.min(2, Math.max(0, limit - 3));
  const vectorShare = limit - keywordShare;
  const vecHits = searchMemoriesByVector({
    agentId: a.agentId,
    category: a.category,
    queryVector: qv,
    limit,
    floor: 0.42, // match recall: below this a "semantic match" is noise
  });
  const kwHits = keyword();

  const out: MemoryRow[] = [];
  const seen = new Set<number>();
  const take = (rows: MemoryRow[], max: number) => {
    for (const r of rows) {
      if (out.length >= limit || max <= 0) return;
      if (seen.has(r.id)) continue;
      seen.add(r.id);
      out.push(r);
      max--;
    }
  };
  take(vecHits, vectorShare);          // meaning leads and gets the bulk
  take(kwHits, keywordShare);          // keywords get a small guaranteed share (exact ids, numbers)
  take(vecHits, limit - out.length);   // anything keywords did not use goes back to meaning
  return out;
}
